[package]
name = "dsms"
version = "0.1.0"
authors = ["Parshav <parshav@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = '0.11.0'